apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: healthcare
type: Opaque
stringData:
  DB_URL: "postgres://postgres:changeme@postgres-service:5432/healthcare?sslmode=disable"
  JWT_SECRET: "change-me-in-production"
  SENTRY_DSN: ""
