export const IMAGING_CONSOLE_LABEL = "HOSPITAL GERAL - PACS CONSOLE"
export const DEFAULT_SERIES_NUMBER = "1"
export const DEFAULT_MODALITY_FALLBACK = "CT"
export const DEFAULT_STUDY_UID_FALLBACK = "1.2.840.10008"
